Refactor manifest search
soos-io/soos-integration-java-core pull request #10
Opened 2022-03-15 12:17 UTC by SOOS-JAlvarez

## Jira Issue:

https://soos.atlassian.net/browse/PA-4171

## Description:

## Tasks / Call outs:

- [x] Refactor manifest search to be recursive
- [x] Perform tests

2022-03-15 13:40 UTC, SOOS-ABenassi requested changes
@SOOS-JAlvarez see my comments

2022-03-15 13:40 UTC, SOOS-ABenassi commented on .gitignore
> +# soos
@SOOS-JAlvarez if it will be commented for ever, you should remove it. anyway, I think that it would be uncommented

2022-03-15 13:40 UTC, SOOS-ABenassi commented on src/main/java/io/soos/integration/domain/manifest/Manifest.java
> +                       return null;
@SOOS-JAlvarez I'n not sure if it should return null or an empty list/array

2022-03-15 13:48 UTC, SOOS-JAlvarez commented on .gitignore
> +# soos
done

2022-03-17 12:01 UTC, SOOS-ABenassi submitted a review, later dismissed
See my comments

2022-03-17 12:01 UTC, SOOS-ABenassi commented on src/main/java/io/soos/integration/domain/manifest/Manifest.java
> +                           System.exit(1);
@SOOS-JAlvarez we should re throw a proper exception and handle the system.exit in only one place

2022-03-17 17:34 UTC, SOOS-JAlvarez commented on .gitignore
> -soos
explained in teams

2022-03-17 17:34 UTC, SOOS-JAlvarez commented on src/main/java/io/soos/integration/domain/manifest/Manifest.java
> +                           System.exit(1);
done

2022-03-17 18:13 UTC, merged